var private_challenges = [
    {
      "name": "MIRA EL DOCUMENTAL “SHE’S BEAUTIFUL WHEN SHE’S ANGRY”."
    },
    {
      "name": "BUSCA 3 LÍDERES FEMINISTAS Y AVERIGUAR SUS CONTRIBUCIONES."
    },
    {
      "name": "BUSCA 5 DEMANDAS DEL FEMINISMO."
    },
    {
      "name": "PRONÚNCIATE AL RECONOCER UN COMENTARIO DEGRINANTE HACIA LA MUJER."
    },
    {
      "name": "REFLEXIONA SOBRE FRASES QUE UNO HA DICHO EN LA COTIDIANIDAD QUE ATRIBUYAN A LA DESIGUALDAD."
    },
    {
      "name": "LEE UN LIBRO RELACIONADO AL FEMINISMO."
    }
  ];
